# Generated by Django 4.1.2 on 2022-11-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_languages_projects_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='profile',
            field=models.ForeignKey(default='No profile', on_delete=django.db.models.deletion.CASCADE, to='profiles_app.profile'),
        ),
        migrations.AddField(
            model_name='projects',
            name='profile',
            field=models.ForeignKey(default='No profile', on_delete=django.db.models.deletion.CASCADE, to='profiles_app.profile'),
        ),
    ]
