# Generated by Django 4.1.2 on 2022-11-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="Hey There I'm using Bloggy"),
        ),
    ]
